In [3]:
# Import dependencies.
import pandas as pd
import numpy as np
import requests

In [5]:
# Read and import city_data.csv
city_data_df = pd.read_csv("weather_data\city_data.csv")

city_data_df.head()

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,Kodiak,US,2022-04-26 19:17:36,57.7900,-152.4072,45.91,53,100,12.66
1,Rikitea,PF,2022-04-26 19:17:36,-23.1203,-134.9692,78.24,75,100,22.26
2,Seoul,KR,2022-04-26 19:17:37,37.5683,126.9778,60.19,30,0,9.22
3,Dukat,RU,2022-04-26 19:17:37,62.5500,155.5500,12.52,95,100,4.09
4,Maceio,BR,2022-04-26 19:13:54,-9.6658,-35.7353,78.24,78,75,18.41

In [ ]:
# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

In [6]:
# Starting URL for weather map API call.
url = "https://api.weather.gov/points/{lat},{lon}"

print(url)

https://api.weather.gov/points/{lat},{lon}

In [ ]:
# Create an empty list to hold the forcast data.
city_forcast = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

In [ ]:
# Loop through all the cities in the list.
for i, City in enumerate(city_data_df["Cities"]):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = https://api.weather.gov/points/{"Lat"},{"Lng"}

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1

# Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")