## Deliverable 2. Create a Customer Travel Destinations Map.

In [31]:
# Dependencies and Setup.
import pandas as pd
import requests
import gmaps
import os
import matplotlib.pyplot as plt

# Import API key.
from config import g_key

# Configure gmaps API key.
gmaps.configure(api_key=g_key)

In [10]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Weather
0,0,Busselton,AU,-33.6500,115.3333,55.31,57,0,7.29,clear sky
1,1,Palmer,US,42.1584,-72.3287,65.01,34,100,6.91,overcast clouds
2,2,Lichuan,CN,30.3000,108.8500,60.03,91,100,2.01,overcast clouds
3,3,Khatanga,RU,71.9667,102.5000,15.13,86,100,24.18,overcast clouds
4,4,Saint George,US,37.1041,-113.5841,89.64,11,0,1.99,clear sky

In [11]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [12]:
# 2. Prompt the user to enter minimum and maximum temperature criteria.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 88
What is the maximum temperature you would like for your trip? 98

In [13]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.


# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                      (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Weather
4,4,Saint George,US,37.1041,-113.5841,89.64,11,0,1.99,clear sky
23,23,Sardarpur,IN,22.6780,74.9484,89.04,22,0,13.87,clear sky
49,49,Tessalit,ML,20.1986,1.0114,91.81,12,100,9.08,overcast clouds
110,110,Bustamante,MX,26.5333,-100.5000,95.94,35,0,4.92,clear sky
135,135,Puerto Madero,MX,14.7208,-92.4215,91.60,58,75,6.91,broken clouds

In [14]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID            39
City               39
Country            39
Lat                39
Lng                39
Max Temp           39
Humidity           39
Cloudiness         39
Wind Speed         39
Current Weather    39
dtype: int64

In [15]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.copy()
clean_df.dropna(inplace = True)

clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Weather
4,4,Saint George,US,37.1041,-113.5841,89.64,11,0,1.99,clear sky
23,23,Sardarpur,IN,22.6780,74.9484,89.04,22,0,13.87,clear sky
49,49,Tessalit,ML,20.1986,1.0114,91.81,12,100,9.08,overcast clouds
110,110,Bustamante,MX,26.5333,-100.5000,95.94,35,0,4.92,clear sky
135,135,Puerto Madero,MX,14.7208,-92.4215,91.60,58,75,6.91,broken clouds
170,170,Sabinas Hidalgo,MX,26.5000,-100.1667,97.72,37,16,9.10,few clouds
214,214,Miracema Do Tocantins,BR,-9.5618,-48.3967,88.34,57,87,3.85,overcast clouds
228,228,Mangrul Pir,IN,20.3167,77.3500,93.06,17,3,12.08,clear sky
256,256,Riyadh,SA,24.6877,46.7219,93.34,15,0,9.01,clear sky
258,258,Camargo,MX,27.6667,-105.1667,89.40,8,0,1.32,clear sky
267,267,San Patricio,US,28.0170,-97.5169,89.69,47,0,13.49,clear sky
272,272,Maraba,BR,-5.3686,-49.1178,93.38,52,20,9.22,few clouds
286,286,Tomatlan,MX,19.9333,-105.2500,91.09,39,12,12.12,few clouds
304,304,La Asuncion,VE,11.0333,-63.8628,94.73,52,100,21.85,overcast clouds
322,322,Mirabad,AF,30.4362,61.8383,93.63,10,76,8.16,broken clouds
331,331,Sao Raimundo Das Mangabeiras,BR,-7.0219,-45.4811,91.62,40,4,6.11,clear sky
344,344,Pauini,BR,-7.7136,-66.9764,90.27,48,100,2.89,overcast clouds
379,379,Araouane,ML,18.9048,-3.5265,96.78,13,8,9.33,clear sky
383,383,Bongor,TD,10.2806,15.3722,92.32,32,46,11.27,scattered clouds
392,392,Emilio Carranza,MX,19.9711,-96.6114,89.02,62,27,6.73,scattered clouds
413,413,Doha,QA,25.2867,51.5333,91.38,34,0,18.41,clear sky
418,418,Atar,MR,20.5169,-13.0499,96.55,9,5,7.18,clear sky
424,424,Sardulgarh,IN,29.7000,75.2500,89.78,21,0,7.02,clear sky
429,429,Bilma,NE,18.6853,12.9164,96.64,10,97,7.74,overcast clouds
435,435,Ixtapa,MX,20.7000,-105.2000,93.81,33,85,8.37,overcast clouds
438,438,Kidal,ML,18.4411,1.4078,94.93,14,100,12.50,overcast clouds
452,452,Jizan,SA,17.3333,42.6667,88.74,53,3,4.27,clear sky
456,456,Taoudenni,ML,22.6783,-3.9836,95.86,9,0,9.60,clear sky
458,458,San Diego De Los Banos,CU,22.6467,-83.3697,93.96,36,0,6.96,clear sky
487,487,Tamiahua,MX,21.2667,-97.4500,88.41,66,42,11.70,scattered clouds
491,491,Karmala,IN,18.4167,75.2000,90.39,29,83,15.57,broken clouds
500,500,Jalpan,MX,21.2333,-99.4833,91.87,46,5,5.39,clear sky
524,524,Catalina,US,32.5056,-110.9211,91.49,9,0,3.00,clear sky
548,548,Saint Augustine,US,29.8947,-81.3145,91.11,49,0,11.50,clear sky
593,593,Gainesville,US,29.6516,-82.3248,90.01,52,40,19.57,scattered clouds
611,611,Saint Pete Beach,US,27.7253,-82.7412,90.19,68,33,5.01,scattered clouds
613,613,Coacoyul,MX,17.8058,-99.1100,94.19,16,75,3.56,broken clouds
635,635,Brownsville,US,25.9018,-97.4975,91.98,65,5,1.99,clear sky
692,692,Najran,SA,17.4924,44.1277,88.45,37,41,12.53,scattered clouds

In [16]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Weather", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Weather,Lat,Lng,Hotel Name
4,Saint George,US,89.64,clear sky,37.1041,-113.5841,
23,Sardarpur,IN,89.04,clear sky,22.6780,74.9484,
49,Tessalit,ML,91.81,overcast clouds,20.1986,1.0114,
110,Bustamante,MX,95.94,clear sky,26.5333,-100.5000,
135,Puerto Madero,MX,91.60,broken clouds,14.7208,-92.4215,
170,Sabinas Hidalgo,MX,97.72,few clouds,26.5000,-100.1667,
214,Miracema Do Tocantins,BR,88.34,overcast clouds,-9.5618,-48.3967,
228,Mangrul Pir,IN,93.06,clear sky,20.3167,77.3500,
256,Riyadh,SA,93.34,clear sky,24.6877,46.7219,
258,Camargo,MX,89.40,clear sky,27.6667,-105.1667,

In [17]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [18]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df1 = hotel_df.copy()                               # Create duplicate of data
hotel_df1 = hotel_df1.replace(r'^s*$', float('NaN'), regex = True)

clean_hotel_df = hotel_df1.copy()
clean_hotel_df.dropna(inplace = True)

clean_hotel_df

,City,Country,Max Temp,Current Weather,Lat,Lng,Hotel Name
4,Saint George,US,89.64,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
23,Sardarpur,IN,89.04,clear sky,22.6780,74.9484,Shri Maya Lodge
110,Bustamante,MX,95.94,clear sky,26.5333,-100.5000,Hotel Hacienda los Nogales
135,Puerto Madero,MX,91.60,broken clouds,14.7208,-92.4215,DEPARTAMENTOS LA ESTANCIA
170,Sabinas Hidalgo,MX,97.72,few clouds,26.5000,-100.1667,Hotel Real Santiago De Las Sabinas
214,Miracema Do Tocantins,BR,88.34,overcast clouds,-9.5618,-48.3967,Miami Apart Hotel
228,Mangrul Pir,IN,93.06,clear sky,20.3167,77.3500,A one dresess& cloth store Dargha chowk Mangru...
256,Riyadh,SA,93.34,clear sky,24.6877,46.7219,"InterContinental Riyadh, an IHG Hotel"
258,Camargo,MX,89.40,clear sky,27.6667,-105.1667,Hotel Santa Fe
267,San Patricio,US,89.69,clear sky,28.0170,-97.5169,"Motel 6 Sinton, TX"
272,Maraba,BR,93.38,few clouds,-5.3686,-49.1178,Hotel Del Principe
286,Tomatlan,MX,91.09,few clouds,19.9333,-105.2500,El Salvial
304,La Asuncion,VE,94.73,overcast clouds,11.0333,-63.8628,Colinas de Matasiete
331,Sao Raimundo Das Mangabeiras,BR,91.62,clear sky,-7.0219,-45.4811,Hotel Tropical
344,Pauini,BR,90.27,overcast clouds,-7.7136,-66.9764,Casa do Kiwliks
383,Bongor,TD,92.32,scattered clouds,10.2806,15.3722,Oryx Palace
392,Emilio Carranza,MX,89.02,scattered clouds,19.9711,-96.6114,Hotel Carranza Inn
413,Doha,QA,91.38,clear sky,25.2867,51.5333,Movenpick Hotel Doha
418,Atar,MR,96.55,clear sky,20.5169,-13.0499,Oumou Elghoura
424,Sardulgarh,IN,89.78,clear sky,29.7000,75.2500,Shri Balaji Pg
429,Bilma,NE,96.64,overcast clouds,18.6853,12.9164,Expeditions Ténére voyages
435,Ixtapa,MX,93.81,overcast clouds,20.7000,-105.2000,hotel la terminal
452,Jizan,SA,88.74,clear sky,17.3333,42.6667,شهدان. ابوالحجر
458,San Diego De Los Banos,CU,93.96,clear sky,22.6467,-83.3697,Casa Nalúa - Nalúa Enea
487,Tamiahua,MX,88.41,scattered clouds,21.2667,-97.4500,Mission Of The Sun Hotel
491,Karmala,IN,90.39,broken clouds,18.4167,75.2000,Hotel Ashutosh Lodge
500,Jalpan,MX,91.87,clear sky,21.2333,-99.4833,Hotel Mision Jalpan
524,Catalina,US,91.49,clear sky,32.5056,-110.9211,Miraval Arizona Resort & Spa
548,Saint Augustine,US,91.11,clear sky,29.8947,-81.3145,St. George Inn
593,Gainesville,US,90.01,scattered clouds,29.6516,-82.3248,Wyndham Garden Gainesville
611,Saint Pete Beach,US,90.19,scattered clouds,27.7253,-82.7412,Grand Plaza Hotel - St. Pete Beach
613,Coacoyul,MX,94.19,broken clouds,17.8058,-99.1100,Casa Abuelita Natalia
635,Brownsville,US,91.98,clear sky,25.9018,-97.4975,Best Western Hotel Plaza Matamoros
692,Najran,SA,88.45,scattered clouds,17.4924,44.1277,محمد هادي ال فطيح

In [19]:
# 8a. Create the output File (CSV).
output_data_file = "C:\\Users\\Bryan\\UofO Bootcamp\\World_Weather_Analysis\\Vacation_Search\\clean_hotel_df.csv"
# 8b. Export the City_Data into a csv.
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [26]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = '''
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Weather} and {Max Temp}°F</dd>
</dl>'''

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [39]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations)

# Add a heatmap of temperature for the vacation spots.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure.
fig

Figure(layout=FigureLayout(height='420px'))